build:
  binary: telnyx-mock
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
  env:
    - CGO_ENABLED=0

before:
  hooks:
    - make clean
    - go generate ./...

checksum:
  name_template: 'checksums.txt'

env_files:
  # create a token at https://github.com/settings/tokens
  # permissions required:
  #   - write:packages (for uploading the binaries to telnyx-mock)
  #   - repo (for modifying homebrew-telnyx-mock)
  github_token: ~/.config/goreleaser/github_token

archives:
  -
    format_overrides:
      - goos: windows
        format: zip

brews:
  -
    tap:
      owner: team-telnyx
      name: homebrew-telnyx-mock

    commit_author:
      name: Telnyx Engineering
      email: engineering@telnyx.com

    homepage: "https://github.com/team-telnyx/telnyx-mock"

    description: >-
      telnyx-mock is a mock HTTP server that responds like the real Telnyx API.
      It can be used instead of Telnyx's testmode to make test suites integrating
      with Telnyx faster and less brittle.

    plist: |
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
        <dict>
          <key>KeepAlive</key>
          <dict>
            <key>SuccessfulExit</key>
            <false/>
          </dict>
          <key>Label</key>
          <string>#{plist_name}</string>
          <key>ProgramArguments</key>
          <array>
            <string>#{opt_bin}/telnyx-mock</string>
            <string>-http-port</string>
            <string>12111</string>
            <string>-https-port</string>
            <string>12112</string>
          </array>
          <key>RunAtLoad</key>
          <true/>
          <key>WorkingDirectory</key>
          <string>#{var}</string>
          <key>StandardErrorPath</key>
          <string>#{var}/log/telnyx-mock.log</string>
          <key>StandardOutPath</key>
          <string>#{var}/log/telnyx-mock.log</string>
        </dict>
      </plist>

dockers:
  -
    image_templates:
      - "telnyx/telnyx-mock:latest"
      - "telnyx/telnyx-mock:{{ .Tag }}"
    dockerfile: "Dockerfile.goreleaser"
